### PR TITLE
Update gradle api to be compatiable with 7.0

### PR DESCRIPTION
**Pull request by aosen-xiong**

### CODE REVIEW

**Comment by sohah** [comment]
@Ao-senXiong , thank you for your contributions. I think this pull request needs additional changes so we can accept it to the SPF repo. I think we need to make the necessary changes to the gradle version in the distribution/wrapper. We also need to think about the gradle version used in JPF, and sync our efforts. I'll look into the details of this pull request in a few days.

**Comment by sohah** [comment]
@Ao-senXiong , do we need this pull request? Isn't the work on the java-11 pull request subsumes the work contained here? If so I think we can close this one and focus on the Java 11 related changes.

**Comment by sohah** [comment]
@Ao-senXiong, can you please reply to my question above?

**Comment by aosen-xiong** [comment]
@sohah You are right, we can close this one.

**Pull request closed without merging**
